# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.3

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.3.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.3.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/ThoughtWorks/Documents/projects/embedded/pn532

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/ThoughtWorks/Documents/projects/embedded/pn532

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.3.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.3.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ThoughtWorks/Documents/projects/embedded/pn532/CMakeFiles /Users/ThoughtWorks/Documents/projects/embedded/pn532/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ThoughtWorks/Documents/projects/embedded/pn532/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hlp

# Build rule for target.
hlp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hlp
.PHONY : hlp

# fast build rule for target.
hlp/fast:
	$(MAKE) -f CMakeFiles/hlp.dir/build.make CMakeFiles/hlp.dir/build
.PHONY : hlp/fast

#=============================================================================
# Target rules for targets named pn532

# Build rule for target.
pn532: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pn532
.PHONY : pn532

# fast build rule for target.
pn532/fast:
	$(MAKE) -f CMakeFiles/pn532.dir/build.make CMakeFiles/pn532.dir/build
.PHONY : pn532/fast

#=============================================================================
# Target rules for targets named pn532-driver

# Build rule for target.
pn532-driver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pn532-driver
.PHONY : pn532-driver

# fast build rule for target.
pn532-driver/fast:
	$(MAKE) -f CMakeFiles/pn532-driver.dir/build.make CMakeFiles/pn532-driver.dir/build
.PHONY : pn532-driver/fast

#=============================================================================
# Target rules for targets named unit-tests

# Build rule for target.
unit-tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unit-tests
.PHONY : unit-tests

# fast build rule for target.
unit-tests/fast:
	$(MAKE) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/build
.PHONY : unit-tests/fast

#=============================================================================
# Target rules for targets named unity

# Build rule for target.
unity: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unity
.PHONY : unity

# fast build rule for target.
unity/fast:
	$(MAKE) -f CMakeFiles/unity.dir/build.make CMakeFiles/unity.dir/build
.PHONY : unity/fast

hlp/hlp.o: hlp/hlp.c.o

.PHONY : hlp/hlp.o

# target to build an object file
hlp/hlp.c.o:
	$(MAKE) -f CMakeFiles/hlp.dir/build.make CMakeFiles/hlp.dir/hlp/hlp.c.o
.PHONY : hlp/hlp.c.o

hlp/hlp.i: hlp/hlp.c.i

.PHONY : hlp/hlp.i

# target to preprocess a source file
hlp/hlp.c.i:
	$(MAKE) -f CMakeFiles/hlp.dir/build.make CMakeFiles/hlp.dir/hlp/hlp.c.i
.PHONY : hlp/hlp.c.i

hlp/hlp.s: hlp/hlp.c.s

.PHONY : hlp/hlp.s

# target to generate assembly for a file
hlp/hlp.c.s:
	$(MAKE) -f CMakeFiles/hlp.dir/build.make CMakeFiles/hlp.dir/hlp/hlp.c.s
.PHONY : hlp/hlp.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/pn532.dir/build.make CMakeFiles/pn532.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/pn532.dir/build.make CMakeFiles/pn532.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/pn532.dir/build.make CMakeFiles/pn532.dir/main.c.s
.PHONY : main.c.s

pn532-driver/pn532.o: pn532-driver/pn532.c.o

.PHONY : pn532-driver/pn532.o

# target to build an object file
pn532-driver/pn532.c.o:
	$(MAKE) -f CMakeFiles/pn532-driver.dir/build.make CMakeFiles/pn532-driver.dir/pn532-driver/pn532.c.o
.PHONY : pn532-driver/pn532.c.o

pn532-driver/pn532.i: pn532-driver/pn532.c.i

.PHONY : pn532-driver/pn532.i

# target to preprocess a source file
pn532-driver/pn532.c.i:
	$(MAKE) -f CMakeFiles/pn532-driver.dir/build.make CMakeFiles/pn532-driver.dir/pn532-driver/pn532.c.i
.PHONY : pn532-driver/pn532.c.i

pn532-driver/pn532.s: pn532-driver/pn532.c.s

.PHONY : pn532-driver/pn532.s

# target to generate assembly for a file
pn532-driver/pn532.c.s:
	$(MAKE) -f CMakeFiles/pn532-driver.dir/build.make CMakeFiles/pn532-driver.dir/pn532-driver/pn532.c.s
.PHONY : pn532-driver/pn532.c.s

unit-tests/command-tests.o: unit-tests/command-tests.c.o

.PHONY : unit-tests/command-tests.o

# target to build an object file
unit-tests/command-tests.c.o:
	$(MAKE) -f CMakeFiles/pn532.dir/build.make CMakeFiles/pn532.dir/unit-tests/command-tests.c.o
	$(MAKE) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/unit-tests/command-tests.c.o
.PHONY : unit-tests/command-tests.c.o

unit-tests/command-tests.i: unit-tests/command-tests.c.i

.PHONY : unit-tests/command-tests.i

# target to preprocess a source file
unit-tests/command-tests.c.i:
	$(MAKE) -f CMakeFiles/pn532.dir/build.make CMakeFiles/pn532.dir/unit-tests/command-tests.c.i
	$(MAKE) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/unit-tests/command-tests.c.i
.PHONY : unit-tests/command-tests.c.i

unit-tests/command-tests.s: unit-tests/command-tests.c.s

.PHONY : unit-tests/command-tests.s

# target to generate assembly for a file
unit-tests/command-tests.c.s:
	$(MAKE) -f CMakeFiles/pn532.dir/build.make CMakeFiles/pn532.dir/unit-tests/command-tests.c.s
	$(MAKE) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/unit-tests/command-tests.c.s
.PHONY : unit-tests/command-tests.c.s

unity/unity.o: unity/unity.c.o

.PHONY : unity/unity.o

# target to build an object file
unity/unity.c.o:
	$(MAKE) -f CMakeFiles/unity.dir/build.make CMakeFiles/unity.dir/unity/unity.c.o
.PHONY : unity/unity.c.o

unity/unity.i: unity/unity.c.i

.PHONY : unity/unity.i

# target to preprocess a source file
unity/unity.c.i:
	$(MAKE) -f CMakeFiles/unity.dir/build.make CMakeFiles/unity.dir/unity/unity.c.i
.PHONY : unity/unity.c.i

unity/unity.s: unity/unity.c.s

.PHONY : unity/unity.s

# target to generate assembly for a file
unity/unity.c.s:
	$(MAKE) -f CMakeFiles/unity.dir/build.make CMakeFiles/unity.dir/unity/unity.c.s
.PHONY : unity/unity.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... pn532"
	@echo "... rebuild_cache"
	@echo "... unit-tests"
	@echo "... hlp"
	@echo "... edit_cache"
	@echo "... pn532-driver"
	@echo "... unity"
	@echo "... hlp/hlp.o"
	@echo "... hlp/hlp.i"
	@echo "... hlp/hlp.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... pn532-driver/pn532.o"
	@echo "... pn532-driver/pn532.i"
	@echo "... pn532-driver/pn532.s"
	@echo "... unit-tests/command-tests.o"
	@echo "... unit-tests/command-tests.i"
	@echo "... unit-tests/command-tests.s"
	@echo "... unity/unity.o"
	@echo "... unity/unity.i"
	@echo "... unity/unity.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
#	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

